AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Description: serverless authentication app demo

Parameters:
  ClientDomain:
    Type: String
    Description: Domain allowed to use this UserPool
    Default: "https://2zqblfwse0.execute-api.eu-central-1.amazonaws.com"
  Postman:
    Type: String
    Default: "true"
    AllowedValues:
      - "true"
      - "false"

Globals:
  Function:
    Environment:
      Variables:
        STAGE: Prod
        JWT_ISSUER: !Sub "https://cognito-idp.${AWS::Region}.amazonaws.com/${UserPool}"
        CLIENT_POOL_ID: !Ref UserPoolClient
        USERS_TABLE: !Ref UsersTable
        USER_POOL_ID: !Ref UserPool

Conditions:
  UsePostman: !Equals [ !Ref Postman, "true" ]

Resources:
  # TODO: Separate auth to it's own stack
  UserPool:
    Type: AWS::Cognito::UserPool
    Properties:
      Policies:
        PasswordPolicy:
          MinimumLength: 6
      AutoVerifiedAttributes:
        - email

  UserPoolClient:
    Type: AWS::Cognito::UserPoolClient
    Properties:
      UserPoolId: !Ref UserPool
      GenerateSecret: false
      SupportedIdentityProviders:
        - COGNITO
      CallbackURLs:
        - !Ref ClientDomain
        - !If [ UsePostman, https://oauth.pstmn.io/v1/callback, !Ref AWS::NoValue ]
      LogoutURLs:
        - !Ref ClientDomain
        - !If [ UsePostman, https://oauth.pstmn.io/v1/callback, !Ref AWS::NoValue ]
      AllowedOAuthFlowsUserPoolClient: true
      AllowedOAuthFlows:
        - code
        - !If [ UsePostman, implicit, !Ref AWS::NoValue ] # Implicit is only used for testing with postman and should not be in production.
      AllowedOAuthScopes:
        - email
        - openid
        - profile
      ExplicitAuthFlows:
        - USER_PASSWORD_AUTH

  CreateUserFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/handlers/create-user.createUserHandler
      Runtime: nodejs18.x
      Architectures:
        - x86_64
      Description: Create user in the DynamoDB table and Cognito User pool.
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref UsersTable
      Events:
        Api:
          Type: Api
          Properties:
            Path: /user
            Method: POST

  LoginUserFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/handlers/login-user.loginUserHandler
      Runtime: nodejs18.x
      Architectures:
        - x86_64
      Description: Login with Cognito to receive a cookie with JWT.
      Events:
        Api:
          Type: Api
          Properties:
            Path: /user/login
            Method: POST

  GetUserFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/handlers/get-user.getUserHandler
      Runtime: nodejs18.x
      Architectures:
        - x86_64
      MemorySize: 128
      Timeout: 100
      Description: Get users by id from a DynamoDB table (requires auth).
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref UsersTable
      Events:
        Api:
          Type: Api
          Properties:
            Path: /user/{id+}
            RestApiId: !Ref FunctionAuthApi
            Method: GET

  UpdateUserFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/handlers/update-user.updateUserHandler
      Runtime: nodejs18.x
      Architectures:
        - x86_64
      Description: Update user in the DynamoDB table.
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref UsersTable
      Events:
        Api:
          Type: Api
          Properties:
            Path: /user
            RestApiId: !Ref FunctionAuthApi
            Method: PUT

  UsersTable:
    Type: AWS::Serverless::SimpleTable
    Properties:
      PrimaryKey:
        Name: national_id
        Type: String
      TableName: "Users"

  AuthorizeUserFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/handlers/authorize-user.authorizeUserHandler
      Runtime: nodejs18.x
      Architectures:
        - x86_64
      Description: Authorize user to access apis.

  FunctionAuthApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Prod
      Description: Manual authentication API
      Auth:
        DefaultAuthorizer: FunctionAuthorizer
        Authorizers:
          FunctionAuthorizer:
            FunctionPayloadType: REQUEST
            FunctionArn: !GetAtt AuthorizeUserFunction.Arn
            Identity:
              Headers:
                - Authorization

  AuthApi:
    Type: AWS::Serverless::HttpApi
    Properties:
      Description: Connect Cognito to HTTP API
      AccessLogSettings:
        DestinationArn: !GetAtt ApiAccessLogGroup.Arn
        Format: "$context.identity.sourceIp $context.identity.caller $context.identity.user [$context.requestTime] \"$context.httpMethod $context.routeKey $context.protocol\" $context.status $context.responseLength $context.requestId"
      CorsConfiguration:
        AllowMethods:
          - GET
          - PUT
      Auth:
        Authorizers:
          JWTCognito:
            IdentitySource: "$request.header.Authorization"
            JwtConfiguration:
              issuer: !Sub "https://cognito-idp.${AWS::Region}.amazonaws.com/${UserPool}"
              audience:
                - !Ref UserPoolClient
        DefaultAuthorizer: JWTCognito

  ApiAccessLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub "/aws/http-api/${ServerlessRestApi}/access_log"
      RetentionInDays: 30

Outputs:
  WebEndpoint:
    Description: "API Gateway endpoint URL for Prod stage"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/"
